# Generated by Django 3.0.4 on 2020-04-30 20:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('tea_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('price', models.FloatField(default=0)),
                ('favourite', models.ManyToManyField(blank=True, related_name='tea_favourite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('price', models.FloatField(default=0)),
                ('dessert_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('calorific', models.FloatField(default=0)),
                ('favourite', models.ManyToManyField(blank=True, related_name='desserts_favourite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=30)),
                ('coffee_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('gluten_free', models.BooleanField(default=False)),
                ('price', models.FloatField(default=0)),
                ('favourite', models.ManyToManyField(blank=True, related_name='coffee_favourite', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
